"""empty message

Revision ID: 1daee577de90
Revises: bdb4a1573652
Create Date: 2023-11-05 18:35:29.369508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1daee577de90'
down_revision = 'bdb4a1573652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_musics_favorite_id_favorites'), 'favorites', ['favorite_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_favorite_id_favorites'), 'favorites', ['favorite_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_favorite_id_favorites'), type_='foreignkey')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_musics_favorite_id_favorites'), type_='foreignkey')
        batch_op.drop_column('favorite_id')

    # ### end Alembic commands ###
