"""empty message

Revision ID: 1f19b686cd8d
Revises: b24200ec19f1
Create Date: 2023-11-08 21:48:04.834649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f19b686cd8d'
down_revision = 'b24200ec19f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_music_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], name=op.f('fk_user_music_association_music_id_musics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_music_association_user_id_users'))
    )
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_musics_playlist_id_playlists', type_='foreignkey')
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_musics_playlist_id_playlists', 'playlists', ['playlist_id'], ['id'])

    op.drop_table('user_music_association')
    # ### end Alembic commands ###
