"""empty message

Revision ID: 1f3ccd887998
Revises: 75a81caf0394
Create Date: 2023-11-03 13:32:54.454898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3ccd887998'
down_revision = '75a81caf0394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_genre_association',
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_music_genre_association_genre_id_genres')),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], name=op.f('fk_music_genre_association_music_id_musics'))
    )
    op.create_table('playlist_music_association',
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], name=op.f('fk_playlist_music_association_music_id_musics')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_music_association_playlist_id_playlists'))
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_constraint('fk_genres_music_id_musics', type_='foreignkey')
        batch_op.drop_column('music_id')

    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_musics_playlist_id_playlists', type_='foreignkey')
        batch_op.drop_constraint('fk_musics_genre_id_genres', type_='foreignkey')
        batch_op.drop_column('genre_id')
        batch_op.drop_column('playlist_id')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_constraint('fk_playlists_music_id_musics', type_='foreignkey')
        batch_op.drop_column('music_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_playlists_music_id_musics', 'musics', ['music_id'], ['id'])

    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_musics_genre_id_genres', 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key('fk_musics_playlist_id_playlists', 'playlists', ['playlist_id'], ['id'])

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_genres_music_id_musics', 'musics', ['music_id'], ['id'])

    op.drop_table('playlist_music_association')
    op.drop_table('music_genre_association')
    # ### end Alembic commands ###
