"""empty message

Revision ID: 8d42ecb3d9f8
Revises: 1f3ccd887998
Create Date: 2023-11-03 13:47:08.768482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d42ecb3d9f8'
down_revision = '1f3ccd887998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('music_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('music_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
