"""empty message

Revision ID: 916b1277cab0
Revises: 2db3a8389651
Create Date: 2023-11-04 10:12:15.225885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916b1277cab0'
down_revision = '2db3a8389651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_genre_association')
    op.drop_table('playlist_music_association')
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('playlist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_musics_genre_id_genres'), 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_musics_playlist_id_playlists'), 'playlists', ['playlist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_musics_playlist_id_playlists'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_musics_genre_id_genres'), type_='foreignkey')
        batch_op.drop_column('playlist_id')
        batch_op.drop_column('genre_id')

    op.create_table('playlist_music_association',
    sa.Column('playlist_id', sa.INTEGER(), nullable=True),
    sa.Column('music_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], name='fk_playlist_music_association_music_id_musics'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='fk_playlist_music_association_playlist_id_playlists')
    )
    op.create_table('music_genre_association',
    sa.Column('music_id', sa.INTEGER(), nullable=True),
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='fk_music_genre_association_genre_id_genres'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], name='fk_music_genre_association_music_id_musics')
    )
    # ### end Alembic commands ###
