"""empty message

Revision ID: 9275ff612b0c
Revises: 6dd6748493f1
Create Date: 2023-11-02 10:58:32.069284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9275ff612b0c'
down_revision = '6dd6748493f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
