"""empty message

Revision ID: b24200ec19f1
Revises: 2b4beac73aee
Create Date: 2023-11-07 22:39:39.739747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24200ec19f1'
down_revision = '2b4beac73aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('music_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], name='fk_favorites_music_id_musics'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorites_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
