"""empty message

Revision ID: bdb4a1573652
Revises: 916b1277cab0
Create Date: 2023-11-04 20:55:13.542991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb4a1573652'
down_revision = '916b1277cab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_genres_music_id_musics'), 'musics', ['music_id'], ['id'])

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_playlists_music_id_musics'), 'musics', ['music_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlists_music_id_musics'), type_='foreignkey')
        batch_op.drop_column('music_id')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_genres_music_id_musics'), type_='foreignkey')
        batch_op.drop_column('music_id')

    # ### end Alembic commands ###
