"""empty message

Revision ID: d2f43be9cdce
Revises: 1daee577de90
Create Date: 2023-11-05 21:38:23.162080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f43be9cdce'
down_revision = '1daee577de90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_musics_favorite_id_favorites', type_='foreignkey')
        batch_op.drop_column('favorite_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_favorite_id_favorites', type_='foreignkey')
        batch_op.drop_column('favorite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_favorite_id_favorites', 'favorites', ['favorite_id'], ['id'])

    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_musics_favorite_id_favorites', 'favorites', ['favorite_id'], ['id'])

    # ### end Alembic commands ###
